### ISSUE TITLE
Laisser la possibilité de lire des dataframe au lieu de fichiers

### ISSUE THREAD

**Issue by geoffreyaldebert** [etalab/csv-detective#40]
Aujourd'hui csv-detective n'analyse qu'à partir d'un fichier. Laisser la possibilité d'analyser un dataframe également.

**Comment by Pierlou** [comment]
Les modifs sont ici : https://github.com/etalab/csv-detective/tree/allow-full-analysis

**Comment by geoffreyaldebert** [comment]
still ongoing
