### ISSUE TITLE
json as python_type?

### ISSUE THREAD

**Issue by abulte** [etalab/csv-detective#45]
While not a primary type (same as #43), it would be nice to know that a column contains some json.

**Comment by Pierlou** [comment]
How would you like it :

'structured_info': {'python_type': 'string', 'format': 'json', 'score': 1.0}

'structured_info': {'python_type': 'json', 'format': 'json', 'score': 1.0}

'structured_info': {'python_type': 'json', 'format': 'something_else?', 'score': 1.0}

**Comment by Pierlou** [comment]
Currently, geojson are handle as fllows:

'geo_info': {'python_type': 'string', 'format': 'json_geojson', 'score': 1.0}

A solution could be:
- for all json files : 'structured_info': {'python_type': 'json', 'format': 'json', 'score': 1.0}
- for geojson files : 'structured_info': {'python_type': 'json', 'format': 'geojson', 'score': 1.0}

**Comment by abulte** [comment]
Works for me!

**Comment by abulte** [comment]
Solved by #48
